### ISSUE TITLE
update_ngw_from_geojson.py - проверка по полю геометрии

### ISSUE THREAD

**Issue by ABiatov** [nextgis/helper_scripts#2]
Как обновить или добавить объект в NGW если нужно смотреть по геометрии?

Какое **check_field** указывать?
```
update_ngw_from_geojson.py --ngw_url http://gis-naturalist.nextgis.com --ngw_resource_id 443 --ngw_login dataeditor --ngw_password мой_пароль --check_field geometry --filename ./LV_3857.geojson
```
Вернуло следующее сообщение:
```
Traceback (most recent call last):
  File "./update_ngw_from_geojson.py", line 373, in <module>
    externalData=processor.openGeoJson(check_field = args.check_field,filename=args.filename)
  File "./update_ngw_from_geojson.py", line 244, in openGeoJson
    local_result[check_field_val] = dict()        
UnboundLocalError: local variable 'check_field_val' referenced before assignment
```

Как реализовать при помощи этого скрипта проверку по геометрии?

**Comment by trolleway** [comment]
Насколько я помню, в --check_field нужно указать поле с уникальным идентификатором, а проверка того, отличаются ли записи, всегда идёт и по всем атрибутам, и по геометрии

**Comment by ABiatov** [comment]
Указал поле с уникальным идентефикатором `CODE_LV`
```
update_ngw_from_geojson.py --ngw_url http://gis-naturalist.nextgis.com --ngw_resource_id 443 --ngw_login dataeditor --ngw_password мой_пароль --check_field CODE_LV --filename ./LV_3857.geojson
```
В слое реально изменен 1 объект с идентификатором `9`.
Скрипт выполнился и вернул мне:
```
Start synchronisation from /home/narwhale/CloudStation/Project/NGW_POD_PK/Data/Lesnoy_fond/GeoJSON/LV_3857.geojson to http://gis-naturalist.nextgis.com/resource/443
Fetching whole ngw layer
Compare features
update feature #1 <Response [502]>
update feature #3 <Response [502]>
update feature #4 <Response [502]>
update feature #5 <Response [502]>
update feature #6 <Response [502]>
update feature #7 <Response [502]>
update feature #8 <Response [502]>
update feature #10 <Response [502]>
update feature #11 <Response [502]>
update feature #12 <Response [502]>
add new feature #9
```
НО фактически новая фича с идентификатором `9` не появилась:
[http://gis-naturalist.nextgis.com/resource/443](http://gis-naturalist.nextgis.com/resource/443)

Файл из которого пытался обновить содержимое упомянутого выше NGW объекта:
[LV_3857.geojson.zip](https://github.com/nextgis/helper_scripts/files/1813887/LV_3857.geojson.zip)

При повторном выполнении скрипта, ответ идентичный.

В чем может быть дело?
Как сделать, чтоб новый объект появился?

**Comment by trolleway** [comment]
ой, извиняюсь за задержку, мне никогда до этого никто в тикеты не писал. 
Я проверю в течении нескольких дней, но раз он писал  Response [502], то может быть это были глюки на nextgis.com. А может и нет.

**Comment by simgislab** [comment]
reopen if necessary
